services:
  backend:
    build:
      context: ./backend
      target: production
    volumes: !reset []
    command: node dist/server.js
    restart: always

  frontend:
    build:
      context: ./frontend
      target: production
    volumes: !reset []
    ports:
      - "80:80"
    command: nginx -g "daemon off;"
    restart: always
